version: '3.7'
services:
  freeradius5:
    container_name: freeradius5
    restart: unless-stopped
    image: freeradius/freeradius-server:latest
    volumes:
      - "/home/docker-freeradius-ultimo/freeradius/docker/certs/:/etc/raddb/certs/:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/clients.conf:/etc/raddb/clients.conf:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/ldap:/etc/raddb/mods-enabled/ldap:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/ldap:/etc/raddb/mods-enabled/cache_auth:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/ldap:/etc/raddb/mods-enabled/eap:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/inner-tunnel:/etc/raddb/sites-enabled/inner-tunnel:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/dictionary:/etc/raddb/dictionary:ro"
      - "/home/docker-freeradius-ultimo/freeradius/docker/set_group_vlan:/etc/raddb/policy.d/set_group_vlan:ro"
    ports:
      - "1812-1813:1812-1813/udp"
    command: [ "radiusd", "-X" ]
